language: node_js
node_js: stable

install:
- npm install -g gulp
- npm install

# - npm install -g gulp

script:
- hexo g

after_script:
- cd ./public
- git init
- git config user.name "hackshen"
- git config user.email "hackshen.com@gmail.com"
- git add .
- git commit -m "Update docs with TRAVIS-CI."
- git push --force --quiet "https://${HEXO_BLOG}@${GH_REF}" master:master

branches:
only:
- hexo
env:
global:
- GH_REF: github.com/hackshen/hackshen.github.io.git
