language: node_js
node_js: stable
install:
- npm install
script:
- hexo g
after_script:
- cd ./public
- git init
- git config user.name "hackshen"
- git config user.email "hackshen.com@gmail.com"
- git add .
- git commit -m "Update docs"
- git push --force --quiet "https://${SHEN_TOKEN}@${GH_REF}" master:master
branches:
  only:
  - hexo
env:
  global:
  - GH_REF: github.com/hackshen/hackshen.github.io.git --{仓库地址}
addons:
  ssh_known_hosts: 47.100.101.94
before_install:
- openssl aes-256-cbc -K $encrypted_5fda406a4caf_key -iv $encrypted_5fda406a4caf_iv
  -in id_rsa_github.enc -out ~/.ssh/id_rsa_github -d
- chmod 600 ~/.ssh/id_rsa_github
- echo -e "Host 47.100.101.94\nStrictHostKeyChecking no\nHostName 47.100.101.94\nUser root\nIdentityFile ~/.ssh/id_rsa_github\n" >> ~/.ssh/config
- scp -o stricthostkeychecking=no -r public root@47.100.101.94:/
