name: hexo

on:
  push:
    branches: [ hexo ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: hexo
      - name: setNodeVersion
        uses: actions/setup-node@v1
        with:
          node-version: '8.x'
      - name: ssh
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.HEXO_KEY }}
      - name: set ssh
        env:
          SSH_KEY: ${{ secrets.HEXO_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo -e "Host cdn.hackshen.com\nStrictHostKeyChecking no\nHostName cdn.hackshen.com\nUser root\nIdentityFile ~/.ssh/id_rsa_github\n" >> ~/.ssh/config
          # 使用云开发 Github Action 部署
      - name: npm install
        run: |
          npm install
          npx hexo g
      - name: Deploy static to Tencent CloudBase
        id: deployStatic
        uses: TencentCloudBase/cloudbase-action@v1
        with:
          # 云开发的访问密钥 secretId 和 secretKey
          secretId: ${{ secrets.SECRET_ID }}
          secretKey: ${{ secrets.SECRET_KEY }}
          # 云开发的环境id
          envId: ${{ secrets.ENV_ID }}
          # Github 项目静态文件的路径
          staticSrcPath: public
      - name: init rsync
        env:
          USE_SSH: true
          GIT_USER: hackshen
          DEPLOYMENT_BRANCH: test
        run: |
          cd ./public
          git init
          git config user.name "hackshen"
          git config user.email "hackshen.com@gmail.com"
          git add .
          git commit -m "Update docs"
          git push --force --quiet git@github.com:hackshen/hackshen.github.io.git master:master
          rsync -rv --delete -e 'ssh -o stricthostkeychecking=no' ./ root@cdn.hackshen.com:/data/www/blog
